# Generated by Django 4.2.5 on 2023-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
