# Generated by Django 4.2.5 on 2023-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_options_lesson_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date',
            new_name='date_create',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
